name: user_app
description: تطبيق المستخدم لعرض المتاجر والمنتجات.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.1
  firebase_auth: ^4.20.0
  firebase_messaging: ^14.0.0 # تقريبي، تحقق من أحدث إصدار على pub.dev
  overlay_support: ^2.0.0 # تقريبي، تحقق من أحدث إصدار على pub.dev
  shared_preferences: ^2.0.0 # تقريبي، تحقق من أحدث إصدار على pub.dev
  shared_models:
    path: ../shared_modules/shared_models
  shared_services:
    path: ../shared_modules/shared_services
  shared_widgets:
    path: ../shared_modules/shared_widgets

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
