include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # تفعيل قواعد التنسيق الأساسية
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_single_quotes: true
    avoid_print: true
    use_key_in_widget_constructors: true
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    library_private_types_in_public_api: true
    package_api_docs: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    sort_child_properties_last: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_build_context_synchronously: true
    use_full_hex_values_for_flutter_colors: true

analyzer:
  exclude:
    # استبعاد الملفات المولدة تلقائياً
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.mocks.dart'
    - 'lib/generated_plugin_registrant.dart'
  errors:
    # تعطيل بعض الأخطاء مؤقتاً أثناء التطوير
    todo: ignore
    invalid_annotation_target: ignore
