name: rivoo_workspace

# الحزم والتطبيقات الفعلية ضمن مشروع Rivoo
packages:
  - shared_libs
  - admin_panell
  - delivery_app
  - seller_panel
  - user_app

# أوامر Melos مخصصة
command:
  bootstrap:
    # تثبيت التبعيات في كل الحزم
    run: melos exec -- "flutter pub get"

  test:
    # تشغيل اختبارات الوحدات فقط في الحزم التي تحتوي على test
    run: melos exec --dir-exists="test" -- "flutter test"

  analyze:
    # تحليل ثابت للكود في كل الحزم
    run: melos exec -- "flutter analyze ."

  format:
    # تنسيق تلقائي للكود في جميع الملفات
    run: melos exec -- "dart format ."

  upgrade:
    # ترقية جميع التبعيات
    run: melos exec -- "flutter pub upgrade"

  clean:
    # تنظيف كل المخرجات
    run: melos exec -- "flutter clean"

# يمكنك إضافة أوامر مخصصة إضافية حسب الحاجة
