name: admin_panel
description: تطبيق لوحة إدارة النظام.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.8
  shared_models: { path: ../shared_modules/shared_models }
  shared_services: { path: ../shared_modules/shared_services }
  shared_widgets: { path: ../shared_modules/shared_widgets }


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # تأكد من وجود المجلدات المطلوبة أو قم بتعليقها إذا لم تستخدمها حالياً.
  # assets:
  #   - assets/images/
