name: admin_panell
description: تطبيق لوحة إدارة النظام.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=3.2.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: any
  flutter_localizations:
    sdk: flutter
  # إدارة الحالة
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.1


  # Firebase حزم
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  firebase_crashlytics: ^3.4.8
  cloud_functions: ^4.5.8
  cloud_firestore: ^4.13.6
  
  # واجهة المستخدم
  fl_chart: ^0.65.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  
  # إضافة تبعيات مفقودة
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  
  # الحزم المشتركة في المونوربو
  shared_libs:
    path: ../shared_libs

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  mockito: ^5.4.4
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  riverpod_generator: ^2.3.9
  
flutter:
  uses-material-design: true
  generate: true
