name: admin_panell
description: تطبيق لوحة إدارة النظام.
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  # إدارة الحالة
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  
  # Firebase حزم
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_crashlytics: ^4.0.0  # تم تحديث الإصدار لحل التعارض
  cloud_functions: ^5.0.0  # تم تحديث الإصدار لحل التعارض
  cloud_firestore: ^5.6.6
  
  # واجهة المستخدم
  fl_chart: ^0.65.0
  intl: ^0.19.0
  flutter_secure_storage: ^9.0.0
  connectivity_plus: ^5.0.2
  
  # إضافة تبعيات مفقودة
  equatable: ^2.0.5
  dartz: ^0.10.1
  mockito: ^5.4.4
  
  # الحزم المشتركة في المونوربو
  shared_models:
    path: ../shared_modules/shared_models
  shared_services:
    path: ../shared_modules/shared_services
  shared_widgets:
    path: ../shared_modules/shared_widgets
  shared:
    path: ../shared
  shared_core:
    path: ../shared_core
    
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.8
  
flutter:
  uses-material-design: true
