name: seller_panel
description: تطبيق صاحب المتجر.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # إدارة الحالة
  flutter_riverpod: ^2.4.9
  go_router: ^13.0.1
  
  # Firebase حزم
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  firebase_messaging: ^15.2.5
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_crashlytics: ^4.0.0  # تم تحديث الإصدار لحل التعارض

  # إشعارات وتخزين محلي
  overlay_support: ^2.0.0
  flutter_local_notifications: ^19.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

  # Charts
  fl_chart: ^0.65.0

  # واجهة المستخدم
  cached_network_image: ^3.3.1
  intl: ^0.19.0
  connectivity_plus: ^5.0.2

  # HTTP requests
  http: ^1.3.0
  
  # إضافة تبعيات مفقودة
  equatable: ^2.0.5
  dartz: ^0.10.1

  # الحزم المشتركة في المونوربو
  shared_models:
    path: ../shared_modules/shared_models
  shared_services:
    path: ../shared_modules/shared_services
  shared_widgets:
    path: ../shared_modules/shared_widgets
  shared_core:
    path: ../shared_core

  image_picker: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  
  # إضافة دعم ملفات الترجمة
  generate: true
