name: shared_services
description: الخدمات المشتركة بين التطبيقات.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Added dependencies
  firebase_auth: any
  flutter_secure_storage: ^9.0.0
  cloud_firestore: any
  flutter_riverpod: any

  # إضافة shared_models كموديول محلي
  shared_models:
    path: ../shared_models  # المسار النسبي للموديول

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
