name: shared_services
description: الخدمات المشتركة بين التطبيقات.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_secure_storage: ^9.0.0
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.2

  # إضافة shared_models كموديول محلي
  shared_models:
    path: ../shared_models

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
