name: shared_services
description: خدمات مشتركة بين التطبيقات.
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_models: { path: /Users/builder/sdk/app/shared_modules/shared_models }
  shared_widgets: { path: /Users/builder/sdk/app/shared_modules/shared_widgets }
