name: shared_models
description: نماذج بيانات مشتركة بين التطبيقات.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # إضافة تبعيات مفقودة
  equatable: ^2.0.5
  json_annotation: ^4.8.1
  dartz: ^0.10.1

  # Firebase حزم
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Added build runner dependencies
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
