name: shared_models
description: نماذج بيانات مشتركة بين التطبيقات.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Added missing dependencies
  equatable: any
  json_annotation: ^4.8.1
  # End of added dependencies

  # إضافة تخزين Cloud Firestore لتدعم import في هذا الموديول
  cloud_firestore: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  # Added build runner dependencies
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
