name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Analyze code
        run: flutter analyze

      - name: Install dependencies
        run: flutter pub get

      - name: Install Melos & Run Tests
        run: |
          flutter pub global activate melos
          melos bootstrap
          melos run test



