name: Flutter CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze:
    name: تحليل الكود
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: تثبيت التبعيات
        run: |
          cd admin_panell
          flutter pub get
      - name: تحليل الكود
        run: |
          cd admin_panell
          flutter analyze

  test:
    name: اختبار الوحدات
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: تثبيت التبعيات
        run: |
          cd admin_panell
          flutter pub get
      - name: تشغيل اختبارات الوحدة
        run: |
          cd admin_panell
          flutter test

  build_web:
    name: بناء تطبيق الويب
    needs: [analyze, test]
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.0'
          channel: 'stable'
      - name: تثبيت التبعيات
        run: |
          cd admin_panell
          flutter pub get
      - name: بناء تطبيق الويب
        run: |
          cd admin_panell
          flutter build web --release
      - name: تحميل ملفات البناء
        uses: actions/upload-artifact@v3
        with:
          name: web-build
          path: admin_panell/build/web

  deploy_firebase:
    name: نشر التطبيق على Firebase Hosting
    needs: [build_web]
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: تنزيل ملفات البناء
        uses: actions/download-artifact@v3
        with:
          name: web-build
          path: admin_panell/build/web
      - name: نشر على Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          channelId: live
          projectId: your-firebase-project-id  # قم بتغيير هذا إلى معرف مشروع Firebase الخاص بك
          entryPoint: './admin_panell'
